"""
QMIX (Real) Baseline for Non-linear PGG
=========================================
Proper QMIX with monotonic mixing network (Rashid et al., 2018).

Architecture:
  - Per-agent Q-networks: 2-layer MLP -> Q(s_i, a) for 11 discrete actions
  - Mixing network: Q_tot = f(Q_1, ..., Q_n, s) where dQ_tot/dQ_i >= 0
  - Hypernetwork: generates mixing weights from global state s

Key difference from IQL (`cleanrl_iql_pgg.py`):
  IQL: Q_tot = sum(Q_i)  (no interaction)
  QMIX: Q_tot = MixingNet(Q_1,...,Q_n; s)  (monotonic interaction)

This directly addresses the reviewer concern:
"Does value decomposition help escape the Nash Trap?"

Dependencies: NumPy only.
"""
import numpy as np
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(__file__))
from pathlib import Path
from envs.nonlinear_pgg_env import NonlinearPGGEnv

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = PROJECT_ROOT / os.environ.get("ETHICAAI_OUTDIR", "outputs") / "cleanrl_baselines"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# === Hyperparameters ===
HIDDEN_DIM = 64
MIXING_DIM = 32
BUFFER_SIZE = 5000
BATCH_SIZE = 32
GAMMA = 0.99
LR = 3e-4
EPS_START = 1.0
EPS_END = 0.05
EPS_DECAY = 200
TARGET_UPDATE = 10
N_ACTIONS = 11  # 0.0, 0.1, ..., 1.0

N_EPISODES = 300
N_EVAL = 30
N_SEEDS = 20

if os.environ.get("ETHICAAI_FAST") == "1":
    print("  [FAST MODE] N_SEEDS=2, N_EPISODES=10")
    N_SEEDS = 2
    N_EPISODES = 10


def relu(x):
    return np.maximum(0, x)

def relu_grad(x):
    return (x > 0).astype(np.float32)


class QNet:
    """Per-agent Q-network (same as IQL version)."""
    
    def __init__(self, rng, obs_dim=4, hid=HIDDEN_DIM, n_act=N_ACTIONS):
        s = np.sqrt(2.0 / obs_dim)
        self.W1 = rng.randn(obs_dim, hid).astype(np.float32) * s
        self.b1 = np.zeros(hid, dtype=np.float32)
        self.W2 = rng.randn(hid, hid).astype(np.float32) * np.sqrt(2.0 / hid)
        self.b2 = np.zeros(hid, dtype=np.float32)
        self.W3 = rng.randn(hid, n_act).astype(np.float32) * np.sqrt(2.0 / hid)
        self.b3 = np.zeros(n_act, dtype=np.float32)
    
    def forward(self, x):
        self._x = x
        self._z1 = x @ self.W1 + self.b1
        self._h1 = relu(self._z1)
        self._z2 = self._h1 @ self.W2 + self.b2
        self._h2 = relu(self._z2)
        return self._h2 @ self.W3 + self.b3  # Q-values for all actions
    
    def param_count(self):
        return sum(p.size for p in [self.W1, self.b1, self.W2, self.b2, self.W3, self.b3])
    
    def copy_from(self, other):
        for attr in ['W1', 'b1', 'W2', 'b2', 'W3', 'b3']:
            setattr(self, attr, getattr(other, attr).copy())


class MixingNetwork:
    """Monotonic mixing network with hypernetwork-generated weights.
    
    Q_tot = f_mix(Q_1, ..., Q_n; state)
    where weights are generated by hypernetworks from global state,
    and monotonicity is enforced via |W| (absolute value).
    
    Architecture:
      - hyper_W1(state) -> W1 of shape (n_agents, mixing_dim)
      - hyper_b1(state) -> b1 of shape (mixing_dim,)
      - hyper_W2(state) -> W2 of shape (mixing_dim, 1)
      - hyper_b2(state) -> b2 of shape (1,)        [no abs, allows bias]
    """
    
    def __init__(self, rng, n_agents, state_dim=4, mixing_dim=MIXING_DIM):
        self.n_agents = n_agents
        self.mixing_dim = mixing_dim
        
        # Hypernetwork for W1: state_dim -> n_agents * mixing_dim
        s1 = np.sqrt(2.0 / state_dim)
        self.hw1_W = rng.randn(state_dim, n_agents * mixing_dim).astype(np.float32) * s1
        self.hw1_b = np.zeros(n_agents * mixing_dim, dtype=np.float32)
        
        # Hypernetwork for b1: state_dim -> mixing_dim
        self.hb1_W = rng.randn(state_dim, mixing_dim).astype(np.float32) * s1
        self.hb1_b = np.zeros(mixing_dim, dtype=np.float32)
        
        # Hypernetwork for W2: state_dim -> mixing_dim * 1
        self.hw2_W = rng.randn(state_dim, mixing_dim).astype(np.float32) * s1
        self.hw2_b = np.zeros(mixing_dim, dtype=np.float32)
        
        # Hypernetwork for b2: state_dim -> 1 (2-layer for expressivity)
        s2 = np.sqrt(2.0 / state_dim)
        self.hb2_W1 = rng.randn(state_dim, mixing_dim).astype(np.float32) * s2
        self.hb2_b1 = np.zeros(mixing_dim, dtype=np.float32)
        self.hb2_W2 = rng.randn(mixing_dim, 1).astype(np.float32) * np.sqrt(2.0 / mixing_dim)
        self.hb2_b2 = np.zeros(1, dtype=np.float32)
        
        # Adam optimizer state
        self._params = ['hw1_W', 'hw1_b', 'hb1_W', 'hb1_b',
                        'hw2_W', 'hw2_b', 'hb2_W1', 'hb2_b1', 'hb2_W2', 'hb2_b2']
        self._m = {k: np.zeros_like(getattr(self, k)) for k in self._params}
        self._v = {k: np.zeros_like(getattr(self, k)) for k in self._params}
        self._t = 0
    
    def forward(self, agent_qs, state):
        """
        agent_qs: (n_agents,) individual Q-values
        state: (state_dim,) global state
        returns: scalar Q_tot
        """
        # Cache for backward pass
        self._state = state.copy()
        self._agent_qs = agent_qs.copy()
        
        # Generate mixing weights from state via hypernetworks
        self._W1_raw = (state @ self.hw1_W + self.hw1_b).reshape(self.n_agents, self.mixing_dim)
        W1 = np.abs(self._W1_raw)  # MONOTONICITY CONSTRAINT
        self._W1 = W1
        b1 = state @ self.hb1_W + self.hb1_b
        self._b1 = b1
        
        self._W2_raw = (state @ self.hw2_W + self.hw2_b).reshape(self.mixing_dim, 1)
        W2 = np.abs(self._W2_raw)  # MONOTONICITY CONSTRAINT
        self._W2 = W2
        
        # b2 from 2-layer hypernetwork
        self._h_b2_pre = state @ self.hb2_W1 + self.hb2_b1
        self._h_b2 = relu(self._h_b2_pre)
        b2 = (self._h_b2 @ self.hb2_W2 + self.hb2_b2).flatten()
        self._b2 = b2
        
        # Forward: agent_qs -> hidden -> Q_tot
        self._z_hidden = agent_qs @ W1 + b1
        self._hidden = relu(self._z_hidden)
        q_tot = (self._hidden @ W2 + b2).item()
        
        return q_tot
    
    def backward(self, td_error):
        """Backprop through mixer. Returns dQ_tot/dQ_i for each agent."""
        state = self._state
        
        # dL/dQ_tot = td_error
        # Q_tot = hidden @ W2 + b2
        # dQ_tot/dhidden = W2.flatten() , shape (mixing_dim,)
        d_hidden = td_error * self._W2.flatten()
        
        # Through relu
        d_z_hidden = d_hidden * (self._z_hidden > 0).astype(np.float32)
        
        # dQ_tot/dQ_i = d_z_hidden @ W1[i,:] => shape (n_agents,)
        d_agent_qs = d_z_hidden @ self._W1.T  # (n_agents,)
        
        # --- Gradients for hypernetwork parameters ---
        # W2 gradient: dL/dW2 = hidden^T * td_error, through abs
        d_W2 = td_error * self._hidden.reshape(-1, 1)
        d_W2_raw = d_W2 * np.sign(self._W2_raw)  # through |.|
        # hw2: W2_raw = state @ hw2_W + hw2_b
        d_hw2_W = np.outer(state, d_W2_raw.flatten())
        d_hw2_b = d_W2_raw.flatten()
        
        # W1 gradient: dL/dW1 = agent_qs^T @ d_z_hidden, through abs
        d_W1 = np.outer(self._agent_qs, d_z_hidden)  # (n_agents, mixing_dim)
        d_W1_raw = d_W1 * np.sign(self._W1_raw)
        d_W1_flat = d_W1_raw.flatten()
        d_hw1_W = np.outer(state, d_W1_flat)
        d_hw1_b = d_W1_flat
        
        # b1 gradient: dL/db1 = d_z_hidden
        d_hb1_W = np.outer(state, d_z_hidden)
        d_hb1_b = d_z_hidden.copy()
        
        # b2 gradient (through 2-layer hypernetwork)
        d_b2 = td_error  # scalar
        d_hb2_W2 = np.outer(self._h_b2, [d_b2])
        d_hb2_b2 = np.array([d_b2])
        d_h_b2 = d_b2 * self.hb2_W2.flatten()
        d_h_b2_pre = d_h_b2 * (self._h_b2_pre > 0).astype(np.float32)
        d_hb2_W1 = np.outer(state, d_h_b2_pre)
        d_hb2_b1 = d_h_b2_pre.copy()
        
        # Collect all gradients
        grads = {
            'hw1_W': d_hw1_W, 'hw1_b': d_hw1_b,
            'hb1_W': d_hb1_W, 'hb1_b': d_hb1_b,
            'hw2_W': d_hw2_W, 'hw2_b': d_hw2_b,
            'hb2_W1': d_hb2_W1, 'hb2_b1': d_hb2_b1,
            'hb2_W2': d_hb2_W2, 'hb2_b2': d_hb2_b2,
        }
        
        # Adam update for mixer
        self._t += 1
        for k in self._params:
            g = grads[k]
            self._m[k] = 0.9 * self._m[k] + 0.1 * g
            self._v[k] = 0.999 * self._v[k] + 0.001 * g**2
            m_hat = self._m[k] / (1 - 0.9**self._t)
            v_hat = self._v[k] / (1 - 0.999**self._t)
            setattr(self, k, getattr(self, k) - LR * m_hat / (np.sqrt(v_hat) + 1e-8))
        
        return d_agent_qs
    
    def param_count(self):
        return sum(getattr(self, k).size for k in self._params)
    
    def copy_from(self, other):
        for k in self._params:
            setattr(self, k, getattr(other, k).copy())
        self._m = {k: np.zeros_like(getattr(self, k)) for k in self._params}
        self._v = {k: np.zeros_like(getattr(self, k)) for k in self._params}
        self._t = 0


class ReplayBuffer:
    def __init__(self, cap=BUFFER_SIZE):
        self.buf = []
        self.pos = 0
        self.cap = cap

    def push(self, item):
        if len(self.buf) < self.cap:
            self.buf.append(item)
        else:
            self.buf[self.pos] = item
        self.pos = (self.pos + 1) % self.cap

    def sample(self, n, rng):
        idx = rng.choice(len(self.buf), n, replace=False)
        return [self.buf[i] for i in idx]

    def __len__(self):
        return len(self.buf)


def bootstrap_ci(data, n_boot=1000, ci=0.95):
    arr = np.array(data)
    boots = np.array([np.mean(np.random.choice(arr, len(arr), replace=True)) for _ in range(n_boot)])
    lo = np.percentile(boots, (1-ci)/2*100)
    hi = np.percentile(boots, (1+ci)/2*100)
    return [float(lo), float(hi)]


def run_qmix(seed):
    """Train QMIX agents on non-linear PGG."""
    rng = np.random.RandomState(42 + seed)
    env = NonlinearPGGEnv(byz_frac=0.3)
    n_honest = env.n_honest
    
    # Per-agent Q-networks
    q_nets = [QNet(np.random.RandomState(seed * 100 + i)) for i in range(n_honest)]
    target_nets = [QNet(np.random.RandomState(seed * 100 + i)) for i in range(n_honest)]
    for i in range(n_honest):
        target_nets[i].copy_from(q_nets[i])
    
    # Mixing network + target
    mixer = MixingNetwork(rng, n_honest)
    target_mixer = MixingNetwork(rng, n_honest)
    target_mixer.copy_from(mixer)
    
    buf = ReplayBuffer()
    
    ep_rewards = []
    ep_lambdas = []
    ep_survivals = []
    
    for ep in range(N_EPISODES):
        obs, _ = env.reset(seed=seed * 10000 + ep)
        eps = EPS_END + (EPS_START - EPS_END) * np.exp(-ep / EPS_DECAY)
        
        total_r, total_lam, steps = 0.0, 0.0, 0
        survived = True
        episode_transitions = []
        
        for t in range(50):
            # Each agent selects action (epsilon-greedy)
            actions = []
            for i in range(n_honest):
                if rng.random() < eps:
                    a = rng.randint(N_ACTIONS)
                else:
                    q_vals = q_nets[i].forward(obs)
                    a = int(np.argmax(q_vals))
                actions.append(a)
            
            lambdas = np.array([a / (N_ACTIONS - 1) for a in actions])
            obs_next, rewards, terminated, truncated, info = env.step(lambdas)
            
            # Store transition
            r_team = float(np.mean(rewards))
            episode_transitions.append((obs.copy(), actions, r_team, obs_next.copy(), terminated))
            
            total_r += r_team
            total_lam += float(lambdas.mean())
            steps += 1
            
            if terminated:
                survived = info.get("survived", False)
                break
            obs = obs_next
        
        # Push episode to buffer
        for trans in episode_transitions:
            buf.push(trans)
        
        # Training: sample mini-batch and update
        if len(buf) >= BATCH_SIZE:
            batch = buf.sample(BATCH_SIZE, rng)
            
            for obs_b, acts_b, r_b, obs_next_b, done_b in batch:
                # Forward: get Q_i(s, a_i) for each agent
                agent_qs = np.array([q_nets[i].forward(obs_b)[acts_b[i]] for i in range(n_honest)])
                
                # Q_tot = MixingNetwork(Q_1, ..., Q_n; s)
                q_tot = mixer.forward(agent_qs, obs_b)
                
                # Target: max_a' Q_i(s', a')
                target_agent_qs = np.array([
                    np.max(target_nets[i].forward(obs_next_b)) for i in range(n_honest)
                ])
                target_q_tot = target_mixer.forward(target_agent_qs, obs_next_b)
                
                y = r_b + (0 if done_b else GAMMA * target_q_tot)
                
                # TD error
                td_error = q_tot - y
                
                # Backprop through mixing network -> per-agent Q-networks
                # mixer.backward() updates mixer weights AND returns dQ_tot/dQ_i
                d_agent_qs = mixer.backward(td_error)
                d_agent_qs = np.clip(d_agent_qs, -10.0, 10.0)  # gradient clipping
                
                for i in range(n_honest):
                    q_vals = q_nets[i].forward(obs_b)
                    dq = np.zeros(N_ACTIONS, dtype=np.float32)
                    dq[acts_b[i]] = d_agent_qs[i]  # weighted by mixer gradient
                    
                    # Backprop through Q-network
                    dW3 = np.outer(q_nets[i]._h2, dq)
                    db3 = dq.copy()
                    
                    d_h2 = (dq @ q_nets[i].W3.T) * relu_grad(q_nets[i]._z2)
                    dW2 = np.outer(q_nets[i]._h1, d_h2)
                    db2 = d_h2.copy()
                    
                    d_h1 = (d_h2 @ q_nets[i].W2.T) * relu_grad(q_nets[i]._z1)
                    dW1 = np.outer(obs_b, d_h1)
                    db1 = d_h1.copy()
                    
                    grads = {'W1': dW1, 'b1': db1, 'W2': dW2, 'b2': db2, 'W3': dW3, 'b3': db3}
                    for k, g in grads.items():
                        param = getattr(q_nets[i], k)
                        setattr(q_nets[i], k, param - LR * g)
        
        # Target network update
        if (ep + 1) % TARGET_UPDATE == 0:
            for i in range(n_honest):
                target_nets[i].copy_from(q_nets[i])
            target_mixer.copy_from(mixer)
        
        ep_rewards.append(total_r / max(steps, 1))
        ep_lambdas.append(total_lam / max(steps, 1))
        ep_survivals.append(float(survived))
        
        if (ep + 1) % 50 == 0:
            r = slice(-30, None)
            w = np.mean(ep_rewards[r])
            l = np.mean(ep_lambdas[r])
            s = np.mean(ep_survivals[r]) * 100
            print(f"    ep {ep+1}: W={w:.1f}, lam={l:.3f}, Surv={s:.0f}%")
    
    # Eval: last N_EVAL episodes
    eval_w = ep_rewards[-N_EVAL:]
    eval_l = ep_lambdas[-N_EVAL:]
    eval_s = ep_survivals[-N_EVAL:]
    
    return {
        "welfare": float(np.mean(eval_w)),
        "lambda": float(np.mean(eval_l)),
        "survival": float(np.mean(eval_s) * 100),
    }


def main():
    print("=" * 65)
    print("  QMIX (Real Mixing Network) Baseline")
    print(f"  N_ACTIONS={N_ACTIONS}, Episodes={N_EPISODES}, Seeds={N_SEEDS}")
    print(f"  Mixing dim={MIXING_DIM}, Monotonicity=|W|")
    print(f"  Total params/agent: ~{QNet(np.random.RandomState(0)).param_count()}")
    print(f"  Mixing network params: ~{MixingNetwork(np.random.RandomState(0), 14).param_count()}")
    print("=" * 65)
    
    t0 = time.time()
    all_results = []
    
    for s in range(N_SEEDS):
        print(f"\n  Seed {s+1}/{N_SEEDS}")
        r = run_qmix(s)
        all_results.append(r)
        print(f"    lam={r['lambda']:.3f}, Surv={r['survival']:.0f}%, W={r['welfare']:.1f}")
    
    lams = [r["lambda"] for r in all_results]
    survs = [r["survival"] for r in all_results]
    welfs = [r["welfare"] for r in all_results]
    
    output = {
        "algorithm": "QMIX (monotonic mixing network)",
        "architecture": {
            "per_agent_q": "2-layer MLP (64 hidden)",
            "mixing_network": "hypernetwork-generated weights with |W| monotonicity",
            "mixing_dim": MIXING_DIM,
        },
        "lambda_mean": float(np.mean(lams)),
        "lambda_std": float(np.std(lams)),
        "lambda_ci95": bootstrap_ci(lams),
        "survival_mean": float(np.mean(survs)),
        "survival_std": float(np.std(survs)),
        "survival_ci95": bootstrap_ci(survs),
        "welfare_mean": float(np.mean(welfs)),
        "welfare_std": float(np.std(welfs)),
        "per_seed_lambda": lams,
        "per_seed_survival": survs,
        "per_seed_welfare": welfs,
        "n_seeds": N_SEEDS,
        "n_episodes": N_EPISODES,
    }
    
    out_path = OUTPUT_DIR / "qmix_real_results.json"
    with open(out_path, 'w') as f:
        json.dump(output, f, indent=2)
    print(f"\n  Saved: {out_path}")
    
    elapsed = time.time() - t0
    print(f"\n{'=' * 65}")
    print(f"  QMIX COMPLETE in {elapsed:.0f}s")
    print(f"  lam={np.mean(lams):.3f}+/-{np.std(lams):.3f}")
    print(f"  Survival={np.mean(survs):.0f}+/-{np.std(survs):.0f}%")
    print(f"  Welfare={np.mean(welfs):.1f}+/-{np.std(welfs):.1f}")
    print(f"{'=' * 65}")


if __name__ == "__main__":
    main()
