#!/usr/bin/env python3
"""
generate_tables.py — Single Source of Truth: JSON → LaTeX tables.

Reads experiment outputs from code/outputs/*.json and generates
LaTeX table *body* files (tabular content only) in paper/tables/.
The paper includes these via \\input{tables/tab_*.tex} inside
\\begin{table} environments that own the caption/label/footnotes.

This structural separation makes manual copy-paste IMPOSSIBLE:
- Numbers live ONLY in JSON
- Table bodies are ONLY machine-generated
- Captions/footnotes stay in unified_paper.tex (human-authored)
- CI enforces: `python generate_tables.py --check`

Usage:
    python generate_tables.py          # Generate all table bodies
    python generate_tables.py --check  # CI: compare generated vs committed
"""
import json
import os
import sys
import hashlib
import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUTS = os.path.join(SCRIPT_DIR, "..", "outputs")
TABLES_DIR = os.path.join(SCRIPT_DIR, "..", "..", "paper", "tables")


def load_json(rel_path):
    p = os.path.join(OUTPUTS, rel_path)
    if not os.path.exists(p):
        print(f"  WARNING: Missing {rel_path}")
        return None
    with open(p) as f:
        return json.load(f)


def fmt(val, decimals=1):
    if isinstance(val, str):
        return val
    return f"{val:.{decimals}f}"


def provenance_comment(json_files):
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [f"% AUTO-GENERATED by generate_tables.py at {ts}",
             f"% DO NOT EDIT MANUALLY — re-run generate_tables.py instead.",
             f"% Source JSON files:"]
    for jf in json_files:
        p = os.path.join(OUTPUTS, jf)
        if os.path.exists(p):
            h = hashlib.md5(open(p, 'rb').read()).hexdigest()[:8]
            lines.append(f"%   {jf} (md5:{h})")
    return "\n".join(lines)


# ================================================================
# tab_emergence: matches unified_paper.tex L277-333 schema exactly
# 5 columns: Method | Params/agent | λ̄ | Survival % | Welfare
# ================================================================
def generate_tab_emergence():
    sources = [
        "ppo_nash_trap/ippo_results.json",
        "cleanrl_baselines/cleanrl_baseline_results.json",
        "cleanrl_baselines/iql_baseline_results.json",
        "cleanrl_baselines/qmix_baseline_results.json",
        "cleanrl_baselines/lola_results.json",
    ]

    ppo = load_json("ppo_nash_trap/ippo_results.json")
    cleanrl = load_json("cleanrl_baselines/cleanrl_baseline_results.json")
    iql_data = load_json("cleanrl_baselines/iql_baseline_results.json")
    qmix_data = load_json("cleanrl_baselines/qmix_baseline_results.json")
    lola_data = load_json("cleanrl_baselines/lola_results.json")

    lines = []
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("\\textbf{Method} & \\textbf{Params/agent} & $\\boldsymbol{\\bar{\\lambda}}$ & \\textbf{Survival \\%} & \\textbf{Welfare} \\\\")
    lines.append("\\midrule")

    # REINFORCE variants
    if ppo:
        algos = ppo.get("algorithms", {})
        for key, label, params in [
            ("ippo_linear", "Ind.\\ REINFORCE Linear", "5"),
            ("ippo_mlp", "Ind.\\ REINFORCE MLP", "161"),
            ("ippo_mlp_critic", "Ind.\\ REINFORCE MLP + Critic", "322"),
        ]:
            a = algos.get(key, {})
            lines.append(f"{label} & {params} & {fmt(a.get('lambda_mean',0), 3)} $\\pm$ {fmt(a.get('lambda_std',0), 3)} & {fmt(a.get('survival_mean',0))} & {fmt(a.get('welfare_mean',0))} \\\\")

    lines.append("\\midrule")
    lines.append("\\multicolumn{5}{c}{\\textit{PPO / Value Decomposition / Opponent-Shaping (20 seeds)}} \\\\")
    lines.append("\\midrule")

    # IPPO
    if cleanrl:
        ippo = cleanrl.get("CleanRL IPPO", {})
        lam = ippo.get("lambda", {})
        surv = ippo.get("survival", {})
        welf = ippo.get("welfare", {})
        lines.append(f"IPPO~\\citep{{schulman2017proximal}} & 4,546 & {fmt(lam.get('mean',0), 3)} $\\pm$ {fmt(lam.get('std',0), 3)} & {fmt(surv.get('mean',0))} & {fmt(welf.get('mean',0))} \\\\")

        mappo = cleanrl.get("CleanRL MAPPO", {})
        lam_m = mappo.get("lambda", {})
        surv_m = mappo.get("survival", {})
        welf_m = mappo.get("welfare", {})
        lines.append(f"MAPPO~\\citep{{yu2022surprising}} & 4,546$^\\dagger$ & {fmt(lam_m.get('mean',0), 3)} $\\pm$ {fmt(lam_m.get('std',0), 3)} & {fmt(surv_m.get('mean',0))} & {fmt(welf_m.get('mean',0))} \\\\")

    # IQL
    if iql_data:
        iql = iql_data.get("CleanRL IQL", {})
        lam = iql.get("lambda", {})
        surv = iql.get("survival", {})
        welf = iql.get("welfare", {})
        lines.append(f"IQL$^\\ddagger$ & 5,195 & {fmt(lam.get('mean',0), 3)} $\\pm$ {fmt(lam.get('std',0), 3)} & {fmt(surv.get('mean',0))} & {fmt(welf.get('mean',0))} \\\\")

    # QMIX
    if qmix_data:
        qmix = qmix_data.get("CleanRL QMIX", {})
        lam = qmix.get("lambda", {})
        surv = qmix.get("survival", {})
        welf = qmix.get("welfare", {})
        lines.append(f"QMIX$^\\S$~\\citep{{rashid2018qmix}} & 7,948$^\\|$ & {fmt(lam.get('mean',0), 3)} $\\pm$ {fmt(lam.get('std',0), 3)} & {fmt(surv.get('mean',0))} & {fmt(welf.get('mean',0))} \\\\")

    # LOLA
    if lola_data:
        lines.append(f"LOLA$^{{\\#}}$~\\citep{{foerster2018learning}} & 5 & {fmt(lola_data.get('lambda_mean',0), 3)} $\\pm$ {fmt(lola_data.get('lambda_std',0), 3)} & {fmt(lola_data.get('survival_mean',0))} & {fmt(lola_data.get('welfare_mean',0))} \\\\")

    lines.append("\\midrule")
    lines.append("Fixed $\\lambda=0.0$ & --- & 0.000 & 0.0 & 20.0 \\\\")
    lines.append("Fixed $\\lambda=1.0$ (oracle) & --- & 1.000 & \\textbf{100.0} & \\textbf{32.0} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\multicolumn{5}{l}{\\small All learned baselines follow CleanRL~\\citep{huang2022cleanrl} single-file conventions (lightweight NumPy; no PyTorch).} \\\\")
    lines.append("\\multicolumn{5}{l}{\\small HP sweep (20 combos $\\times$ 10 seeds, Appendix~\\ref{app:hp_sweep}) confirms the Nash Trap persists across all 200 tested configurations.} \\\\")
    lines.append("\\multicolumn{5}{l}{\\small $^\\dagger$Plus shared critic. $^\\ddagger$IQL = no mixing network. $^\\S$Monotonic mixing via hypernetwork-generated $|W|$.} \\\\")
    lines.append("\\multicolumn{5}{l}{\\small $^\\|$Per-agent Q + mixing net. Canonical PyTorch QMIX at $N{=}5$ (20 seeds) confirms Nash Trap (Appendix~\\ref{app:canonical_qmix}).} \\\\")
    lines.append("\\multicolumn{5}{l}{\\small $^{\\#}$QMIX \\& LOLA: 2 seeds each; QMIX's per-agent Q-learning and LOLA's $O(N^2)$ cross-derivative limit large-seed runs.} \\\\")
    lines.append("\\end{tabular}")

    return provenance_comment(sources) + "\n" + "\n".join(lines) + "\n"


# ================================================================
# tab_stress_test: matches unified_paper.tex L277-287 schema exactly
# 5 columns: Condition | Selfish RL | Situational | Unconditional | Tail_5
# ================================================================
def generate_tab_stress():
    data = load_json("stress_test/stress_test_results.json")
    if not data:
        return "% MISSING: stress_test_results.json\n"

    sources = ["stress_test/stress_test_results.json"]
    cond_order = ["baseline_severe", "near_tipping_start", "long_horizon",
                  "shock_burst", "combined_worst"]
    cond_labels = {
        "baseline_severe": "Baseline severe",
        "near_tipping_start": "Near-tipping ($R_0{=}0.17$)",
        "long_horizon": "Long horizon ($T{=}200$)",
        "shock_burst": "Shock burst ($p{=}0.15$)",
        "combined_worst": "Combined worst",
    }
    policy_order = ["selfish_rl", "situational", "unconditional"]
    # Rows that get bold on unconditional
    bold_rows = {"near_tipping_start", "shock_burst", "combined_worst"}

    lines = []
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\toprule")
    lines.append("\\textbf{Stress Condition} & \\textbf{Selfish RL} & \\textbf{Situational} & \\textbf{Unconditional} & \\textbf{Tail$_5$} \\\\")
    lines.append("\\midrule")

    for cond in cond_order:
        cond_data = data.get(cond, {})
        policies = cond_data.get("policies", {})
        vals = []
        for pol in policy_order:
            surv = policies.get(pol, {}).get("survival_mean", 0)
            vals.append(surv)

        label = cond_labels.get(cond, cond)
        selfish_s = f"{fmt(vals[0])}\\%"
        sit_s = f"{fmt(vals[1])}\\%"
        # Bold unconditional for key stress rows
        if cond in bold_rows:
            uncond_s = f"\\textbf{{{fmt(vals[2])}\\%}}"
        else:
            uncond_s = f"{fmt(vals[2])}\\%"

        # Tail_5: 5th percentile of unconditional survival across seeds
        uncond_per_seed = policies.get("unconditional", {}).get("per_seed_survival", [])
        if uncond_per_seed and len(uncond_per_seed) >= 5:
            tail5 = sorted(uncond_per_seed)[0]  # worst seed as proxy for tail
            tail5_s = f"{fmt(tail5)}\\%"
        else:
            tail5_s = f"{fmt(vals[2])}\\%"  # fallback: use mean

        lines.append(f"{label} & {selfish_s} & {sit_s} & {uncond_s} & {tail5_s} \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    return provenance_comment(sources) + "\n" + "\n".join(lines) + "\n"


# ================================================================
# tab_scale: matches unified_paper.tex L367-377 schema exactly
# 4 columns: Method (N=100) | Welfare | λ̄ | Survival %
# ================================================================
def generate_tab_scale():
    data = load_json("scale_n100/scale_n100_results.json")
    if not data:
        return "% MISSING: scale_n100_results.json\n"

    sources = ["scale_n100/scale_n100_results.json"]
    results = data.get("results", [])

    lines = []
    lines.append("\\begin{tabular}{lccc}")
    lines.append("\\toprule")
    lines.append("\\textbf{Method ($N{=}100$)} & \\textbf{Welfare} & $\\boldsymbol{\\bar{\\lambda}}$ & \\textbf{Survival \\%} \\\\")
    lines.append("\\midrule")

    for i, entry in enumerate(results):
        label = entry.get("label", "Unknown")
        welf = entry.get("welfare_mean", 0)
        lam = entry.get("lambda_mean", 0)
        surv = entry.get("survival_mean", 0)

        # Escape % for LaTeX
        label = label.replace("%", "\\%")

        # Add LaTeX superscript for Selfish RL entries
        if "Selfish" in label:
            tex_label = label.replace("Selfish RL", "Selfish RL$^\\dagger$")
        else:
            tex_label = label

        # Bold low survival
        if surv < 60:
            surv_s = f"\\textbf{{{fmt(surv)}}}"
        else:
            surv_s = fmt(surv)

        lines.append(f"{tex_label} & {fmt(welf)} & {fmt(lam, 3)} & {surv_s} \\\\")

        # Midrule after selfish rows (2 selfish entries)
        if i == 1:
            lines.append("\\midrule")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")

    return provenance_comment(sources) + "\n" + "\n".join(lines) + "\n"


# ================================================================
# Main
# ================================================================
def main():
    os.makedirs(TABLES_DIR, exist_ok=True)

    tables = {
        "tab_emergence.tex": generate_tab_emergence,
        "tab_stress_test.tex": generate_tab_stress,
        "tab_scale.tex": generate_tab_scale,
    }

    check_mode = "--check" in sys.argv
    all_ok = True

    for fname, gen_fn in tables.items():
        content = gen_fn()
        fpath = os.path.join(TABLES_DIR, fname)

        if check_mode:
            if os.path.exists(fpath):
                with open(fpath, 'r', encoding='utf-8') as f:
                    existing = f.read()
                # Skip provenance timestamp line for comparison
                def strip_ts(s):
                    return "\n".join(l for l in s.splitlines()
                                    if not l.startswith("% AUTO-GENERATED"))
                if strip_ts(existing) != strip_ts(content):
                    print(f"  MISMATCH: {fname}")
                    all_ok = False
                else:
                    print(f"  OK: {fname}")
            else:
                print(f"  MISSING: {fname}")
                all_ok = False
        else:
            with open(fpath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"  Generated: {fpath}")

    if check_mode and not all_ok:
        print("\nFAIL: Tables out of sync with JSON. Run: python generate_tables.py")
        sys.exit(1)
    elif check_mode:
        print("\nOK: All tables match JSON sources.")

    # --- SSOT Connectivity Check (--check mode only) ---
    if check_mode:
        all_ok = verify_ssot_connectivity() and all_ok
        if not all_ok:
            sys.exit(1)


def strip_latex_comments(text):
    """Remove LaTeX comments (lines starting with %, or inline % not escaped)."""
    import re
    return re.sub(r"(?<!\\)%.*", "", text)


def extract_table_block(src, label_str):
    r"""Extract \begin{table}...\end{table} block containing the given label."""
    idx = src.find(label_str)
    if idx < 0:
        return None
    begin = src.rfind(r"\begin{table", 0, idx)
    end = src.find(r"\end{table}", idx)
    if begin < 0 or end < 0:
        return None
    return src[begin:end + len(r"\end{table}")]


def verify_ssot_connectivity():
    """Verify that unified_paper.tex uses \\input for SSOT tables and has no inline bypass."""
    import re
    paper_path = os.path.join(TABLES_DIR, "..", "unified_paper.tex")
    if not os.path.exists(paper_path):
        print("\n  SKIP: unified_paper.tex not found (connectivity check)")
        return True

    with open(paper_path, 'r', encoding='utf-8') as f:
        raw = f.read()
    src = strip_latex_comments(raw)

    ssot_tables = [
        ("tab:emergence", "tab_emergence"),
        ("tab:stress_test", "tab_stress_test"),
        ("tab:scale", "tab_scale"),
    ]

    print("\n--- SSOT Connectivity Check ---")
    ok = True

    for label, fname_base in ssot_tables:
        label_str = r"\label{" + label + "}"
        block = extract_table_block(src, label_str)
        if block is None:
            print(f"  WARN: Cannot find table block for {label}")
            continue

        # Check 1: \input{tables/tab_*} must exist (with or without .tex)
        input_pat = re.compile(
            r"\\input\{tables/" + re.escape(fname_base) + r"(\.tex)?\}"
        )
        if not input_pat.search(block):
            print(f"  FAIL: {label} missing \\input{{tables/{fname_base}}}")
            ok = False
        else:
            print(f"  OK: {label} uses \\input{{tables/{fname_base}}}")

        # Check 2: No inline \begin{tabular} in the same table block
        # (The tabular should come ONLY from the \input'd file)
        # Allow \resizebox wrapping but not raw tabular
        if r"\begin{tabular" in block:
            print(f"  FAIL: {label} has inline \\begin{{tabular}} (SSOT bypass)")
            ok = False
        else:
            print(f"  OK: {label} has no inline tabular (SSOT enforced)")

    if ok:
        print("OK: All SSOT tables are \\input-linked (no inline bypass).\n")
    else:
        print("FAIL: SSOT connectivity violated -- fix unified_paper.tex.\n")

    return ok


if __name__ == "__main__":
    main()
