#!/usr/bin/env python3
"""
generate_tables.py — Single Source of Truth: JSON → LaTeX tables.

Reads experiment outputs from code/outputs/*.json and generates
LaTeX table files in paper/tables/. The paper includes these via
\\input{tables/tab_*.tex}, eliminating manual copy-paste errors.

Usage:
    python generate_tables.py          # Generate all tables
    python generate_tables.py --check  # Compare generated vs committed (CI mode)
"""
import json
import os
import sys
import hashlib
import datetime

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUTS = os.path.join(SCRIPT_DIR, "..", "outputs")
TABLES_DIR = os.path.join(SCRIPT_DIR, "..", "..", "paper", "tables")


def load_json(rel_path):
    p = os.path.join(OUTPUTS, rel_path)
    if not os.path.exists(p):
        print(f"  WARNING: Missing {rel_path}")
        return None
    with open(p) as f:
        return json.load(f)


def fmt(val, decimals=1):
    """Format a number to fixed decimals."""
    if isinstance(val, str):
        return val
    return f"{val:.{decimals}f}"


def provenance_comment(json_files):
    """Generate a LaTeX comment with provenance info."""
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [f"% AUTO-GENERATED by generate_tables.py at {ts}",
             f"% DO NOT EDIT MANUALLY — re-run generate_tables.py instead.",
             f"% Source JSON files:"]
    for jf in json_files:
        p = os.path.join(OUTPUTS, jf)
        if os.path.exists(p):
            h = hashlib.md5(open(p, 'rb').read()).hexdigest()[:8]
            lines.append(f"%   {jf} (md5:{h})")
    return "\n".join(lines)


# ================================================================
# Table: tab_emergence (Cooperation failure across algorithms)
# ================================================================
def generate_tab_emergence():
    sources = [
        "ppo_nash_trap/ippo_results.json",
        "cleanrl_baselines/cleanrl_baseline_results.json",
        "cleanrl_baselines/iql_baseline_results.json",
        "cleanrl_baselines/qmix_baseline_results.json",
        "cleanrl_baselines/lola_results.json",
    ]

    ppo = load_json("ppo_nash_trap/ippo_results.json")
    cleanrl = load_json("cleanrl_baselines/cleanrl_baseline_results.json")
    iql_data = load_json("cleanrl_baselines/iql_baseline_results.json")
    qmix_data = load_json("cleanrl_baselines/qmix_baseline_results.json")
    lola_data = load_json("cleanrl_baselines/lola_results.json")

    rows = []

    # REINFORCE variants from ppo_nash_trap
    if ppo:
        algos = ppo.get("algorithms", {})
        for key, label, params in [
            ("ippo_linear", "Ind.\\ REINFORCE Linear", "5"),
            ("ippo_mlp", "Ind.\\ REINFORCE MLP", "161"),
            ("ippo_mlp_critic", "Ind.\\ REINFORCE MLP + Critic", "322"),
        ]:
            a = algos.get(key, {})
            lam_m = a.get("lambda_mean", 0)
            lam_s = a.get("lambda_std", 0)
            surv = a.get("survival_mean", 0)
            welf = a.get("welfare_mean", 0)
            rows.append(f"{label} & {params} & {fmt(lam_m, 3)} $\\pm$ {fmt(lam_s, 3)} & {fmt(surv)} & {fmt(welf)} \\\\")

    rows.append("\\midrule")
    rows.append("\\multicolumn{5}{c}{\\textit{PPO / Value Decomposition / Opponent-Shaping (20 seeds)}} \\\\")
    rows.append("\\midrule")

    # CleanRL IPPO
    if cleanrl:
        ippo = cleanrl.get("CleanRL IPPO", {})
        lam = ippo.get("lambda", {})
        surv = ippo.get("survival", {})
        n_seeds = len(ippo.get("per_seed_lambda", []))
        rows.append(f"IPPO~\\citep{{schulman2017proximal}} & 4,546 & {fmt(lam.get('mean',0), 3)} $\\pm$ {fmt(lam.get('std',0), 3)} & {fmt(surv.get('mean',0))} & {fmt(ippo.get('welfare',{}).get('mean',0))} \\\\")

        mappo = cleanrl.get("CleanRL MAPPO", {})
        lam_m = mappo.get("lambda", {})
        surv_m = mappo.get("survival", {})
        rows.append(f"MAPPO~\\citep{{yu2022surprising}} & 4,546$^\\dagger$ & {fmt(lam_m.get('mean',0), 3)} $\\pm$ {fmt(lam_m.get('std',0), 3)} & {fmt(surv_m.get('mean',0))} & {fmt(mappo.get('welfare',{}).get('mean',0))} \\\\")

    # IQL
    if iql_data:
        iql = iql_data.get("CleanRL IQL", {})
        lam = iql.get("lambda", {})
        surv = iql.get("survival", {})
        rows.append(f"IQL$^\\ddagger$ & 5,195 & {fmt(lam.get('mean',0), 3)} $\\pm$ {fmt(lam.get('std',0), 3)} & {fmt(surv.get('mean',0))} & {fmt(iql.get('welfare',{}).get('mean',0))} \\\\")

    # QMIX
    if qmix_data:
        qmix = qmix_data.get("CleanRL QMIX", {})
        lam = qmix.get("lambda", {})
        surv = qmix.get("survival", {})
        n_seeds_q = len(qmix.get("per_seed_lambda", []))
        rows.append(f"QMIX$^\\S$~\\citep{{rashid2018qmix}} & 7,948$^\\|$ & {fmt(lam.get('mean',0), 3)} $\\pm$ {fmt(lam.get('std',0), 3)} & {fmt(surv.get('mean',0))} & {fmt(qmix.get('welfare',{}).get('mean',0))} \\\\")

    # LOLA
    if lola_data:
        lam_l = lola_data.get("lambda_mean", 0)
        lam_ls = lola_data.get("lambda_std", 0)
        surv_l = lola_data.get("survival_mean", 0)
        welf_l = lola_data.get("welfare_mean", 0)
        n_seeds_l = lola_data.get("n_seeds", 0)
        rows.append(f"LOLA$^{{\\#}}$~\\citep{{foerster2018learning}} & 5 & {fmt(lam_l, 3)} $\\pm$ {fmt(lam_ls, 3)} & {fmt(surv_l)} & {fmt(welf_l)} \\\\")

    rows.append("\\midrule")
    rows.append("Fixed $\\lambda=0.0$ & --- & 0.000 & 0.0 & 20.0 \\\\")
    rows.append("Fixed $\\lambda=1.0$ (oracle) & --- & 1.000 & \\textbf{100.0} & \\textbf{32.0} \\\\")

    content = provenance_comment(sources) + "\n"
    content += "\\begin{tabular}{lcccc}\n\\toprule\n"
    content += "\\textbf{Method} & \\textbf{Params/agent} & $\\boldsymbol{\\bar{\\lambda}}$ & \\textbf{Survival \\%} & \\textbf{Welfare} \\\\\n"
    content += "\\midrule\n"
    content += "\n".join(rows) + "\n"
    content += "\\bottomrule\n\\end{tabular}\n"

    return content


# ================================================================
# Table: tab_scale (N=100)
# ================================================================
def generate_tab_scale():
    data = load_json("scale_n100/scale_n100_results.json")
    if not data:
        return "% MISSING: scale_n100_results.json\n"

    sources = ["scale_n100/scale_n100_results.json"]
    rows = []
    results = data.get("results", [])
    for i, entry in enumerate(results):
        label = entry.get("label", "Unknown")
        welf = entry.get("welfare_mean", 0)
        lam = entry.get("lambda_mean", 0)
        surv = entry.get("survival_mean", 0)
        bold = "\\textbf{" + fmt(surv) + "}" if surv < 60 else fmt(surv)
        rows.append(f"{label} & {fmt(welf)} & {fmt(lam, 3)} & {bold} \\\\")
        if i == 1:
            rows.append("\\midrule")

    content = provenance_comment(sources) + "\n"
    content += "\\begin{tabular}{lccc}\n\\toprule\n"
    content += "\\textbf{Method ($N{=}100$)} & \\textbf{Welfare} & $\\boldsymbol{\\bar{\\lambda}}$ & \\textbf{Survival \\%} \\\\\n"
    content += "\\midrule\n"
    content += "\n".join(rows) + "\n"
    content += "\\bottomrule\n\\end{tabular}\n"

    return content


# ================================================================
# Table: tab_stress_test
# ================================================================
def generate_tab_stress():
    data = load_json("stress_test/stress_test_results.json")
    if not data:
        return "% MISSING: stress_test_results.json\n"

    sources = ["stress_test/stress_test_results.json"]
    cond_order = ["baseline_severe", "near_tipping_start", "long_horizon",
                  "shock_burst", "combined_worst"]
    cond_labels = {
        "baseline_severe": "Baseline severe",
        "near_tipping_start": "Near-tipping ($R_0{=}0.18$)",
        "long_horizon": "Long horizon ($T{=}200$)",
        "shock_burst": "Shock burst ($p{=}0.15$)",
        "combined_worst": "Combined worst-case",
    }
    policy_order = ["selfish_rl", "situational", "unconditional"]

    rows = []
    for cond in cond_order:
        cond_data = data.get(cond, {})
        policies = cond_data.get("policies", {})
        vals = []
        for pol in policy_order:
            surv = policies.get(pol, {}).get("survival_mean", 0)
            vals.append(fmt(surv))
        label = cond_labels.get(cond, cond)
        rows.append(f"{label} & {vals[0]} & {vals[1]} & {vals[2]} \\\\")

    content = provenance_comment(sources) + "\n"
    content += "\\begin{tabular}{lccc}\n\\toprule\n"
    content += "\\textbf{Condition} & \\textbf{Selfish} & \\textbf{Situational} & \\textbf{Unconditional} \\\\\n"
    content += "\\midrule\n"
    content += "\n".join(rows) + "\n"
    content += "\\bottomrule\n\\end{tabular}\n"

    return content


# ================================================================
# Main
# ================================================================
def main():
    os.makedirs(TABLES_DIR, exist_ok=True)

    tables = {
        "tab_emergence.tex": generate_tab_emergence,
        "tab_scale.tex": generate_tab_scale,
        "tab_stress_test.tex": generate_tab_stress,
    }

    check_mode = "--check" in sys.argv
    all_ok = True

    for fname, gen_fn in tables.items():
        content = gen_fn()
        fpath = os.path.join(TABLES_DIR, fname)

        if check_mode:
            if os.path.exists(fpath):
                with open(fpath, 'r', encoding='utf-8') as f:
                    existing = f.read()
                # Skip provenance timestamp line for comparison
                def strip_ts(s):
                    return "\n".join(l for l in s.splitlines()
                                    if not l.startswith("% AUTO-GENERATED"))
                if strip_ts(existing) != strip_ts(content):
                    print(f"  MISMATCH: {fname}")
                    all_ok = False
                else:
                    print(f"  OK: {fname}")
            else:
                print(f"  MISSING: {fname}")
                all_ok = False
        else:
            with open(fpath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"  Generated: {fpath}")

    if check_mode and not all_ok:
        print("\nFAIL: Tables out of sync with JSON. Run: python generate_tables.py")
        sys.exit(1)
    elif check_mode:
        print("\nOK: All tables match JSON sources.")


if __name__ == "__main__":
    main()
